config/routes.rb
EnsaludpsiRails::Application.routes.draw do  
  resources :messages

  resources :categories

  resources :articles

  resources :users
  resources :sessions
  
  resources :questions
  
  root                  :to => 'pages#home'
  
  match '/matypat',     :to => 'pages#mat_y_pat'
  match '/consultorio', :to => 'pages#consultorio'
  match '/contacto',    :to => 'pages#contacto'
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new",     :as => "login"
  get "signup" => "users#new",        :as => "signup"

  match "/toggle_admin" => "users#toggle_admin"
  match "/toggle_editor" => "users#toggle_editor"


end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :categorizations
	has_many :categories, :through => :categorizations
	
	has_many :authorships
	has_many :users, :through => :authorships, :as => :authors
	
	has_many :messages
	
	attr_accessible :title, :contents
	attr_accessible :title, :contents, :user_ids, :category_ids, :as => :editor
	attr_accessible :title, :contents, :user_ids, :category_ids, :published, :as => :admin
	
	validates :title, :presence => true
	validates :contents, :presence => true
	
	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order("updated_at desc").find_all_by_published(true).paginate(:page => params[:page], :per_page => (5 unless params[:all_pages]))
		
			
		@categories = Category.all
		
		if params[:layout] == 'none'
			render :partial => @articles, :layout => nil
		else
			respond_to do |format|
				format.html # index.html.erb
				format.json { render :json => @articles } # index.json
				format.rss
			end
		end
		
    
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
		@categories = Category.all
		@message = Message.new
		
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
		deny_access_unless(admin? || editor?)
    @article = Article.new
		@article.published = false
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
    deny_access_unless(admin? || (editor? && @article.users.include?(current_user)))
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])
		deny_access_unless(admin? || editor?)
		
		opts = {}
		opts[:as]=[]
		
		opts = {}
		opts = { :as => :editor } if editor?
		opts = { :as => :admin } if admin?
		
    respond_to do |format|
      if @article.save(opts)
				@article.update_attributes(params[:article], opts)
        format.html { redirect_to @article, :notice => 'Article was successfully created.' }
        format.json { render :json => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])
		deny_access_unless(can_edit?(@article))
		
		opts = {}
		opts = { :as => :editor } if can_edit?(@article)
		opts = { :as => :admin } if admin?

    respond_to do |format|
      if @article.update_attributes(params[:article], opts)
        format.html { redirect_to @article, :notice => 'Article was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    deny_access_unless(admin?)

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :ok }
    end
  end
  
  private
  
		def deny_access_unless(condition)
			deny_access unless condition
		end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div>
	<span style="font-weight: bold;">
		<%= link_to article.title.capitalize, article %>
	</span>
	<span style="color: gray; font-size: 12px; margin-left: 10px;"><br/>
		(Modificado hace <%= time_ago_in_words(article.updated_at) %>)
	</span>
	<% if can_edit?(article) %>
		<span>
			<%= link_to "Editar", edit_article_path(article) %>
		</span>
	<% end %>
	<% if admin? %>
		| <span>
			<%= link_to 'Eliminar', article, :confirm => 'Está seguro?', :method => :delete %>
		</span>
	<% end %>
</div>

app/views/articles/_form.html.erb
<%= javascript_include_tag "jquery.markitup", "set_markitup" %>

<div class="contentBody">
	<%= semantic_form_for(@article) do |f| %>
		<%= f.buttons %>
		<%= f.inputs do %>
			<%= f.input :title, :label => "Título" %>
			<div class="char_counter">
				<p style="text-align: right; color: gray;"><label>Caracteres: </label>
				<span><%= @article.contents.nil? ? 0 : @article.contents.length %></span></p>
				<%= f.input :contents, :as => :text, :label => "Contenidos", :input_html => { :class => "markItUp" } %>
			</div>
			<%= f.input :users, :label => "Autores", :collection => User.find_all_by_editor(true) %>
			<%= f.input :categories, :label => "Categorías" %>
			<% if admin? %>
				<%= f.input :published, :label => "Publicado?" %>
			<% end %>
		<% end %>
		<%= f.buttons %>
	<% end %>
</div>

app/views/articles/_left_bar.html.erb
<% content_for :left_bar do %>

	<nav id="nav" class="tree-menu">
		<h1>Categorías</h1>
		<ul>
			<% @categories.each do |cat| %>
				<% if cat.has_published_articles? %>
					<li><h2><%= cat.name %></h2>
						<ul>
						<% cat.published_articles.each do |art| %>
							<li><%= link_to art.title.capitalize, art %></li>
						<% end %>
					</ul>
				</li>
				<% end %>
			<% end %>
		</ul>
	</nav>

<% end %>

app/views/articles/_message.html.erb
<li class="comentario">
	<div class="comentario-meta">
		<!-- avatar -->
		<h4><%= link_to message.user.name, message.user %></h4>
		 <span>Hace <%= time_ago_in_words(message.created_at) %>.</span>
		 <% if admin? || current_user?(message.user) %>
			<div><%= link_to 'Eliminar', message, :confirm => 'Está seguro?', :method => :delete %></div>
		 <% end %>
	</div>
	<blockquote>
		<%= markdown message.message %>
	</blockquote>
</li>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render "left_bar" %>
<div class="contents">
	<h2 class="contentTitle">Últimos artículos publicados</h2>
	
	<div class="contentBody">
		<div id="articulos">
			<%= render :partial => @articles %>
		</div>
		
		<% unless @last_page  %>
			<div id="cargando">Cargando más resultados ...</div>
			<div id="cargar_mas_articulos" class="boton">Cargar más artículos</div>
		<% end %>
		
		<% if editor? || admin? %>
			<br><%= link_to 'Crear artículo', new_article_path, :class => :accion %>
		<% end %>
	</div>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= render "left_bar" %>

<div class="contents">
	<p id="notice"><%= notice %></p>

	<h1 class="contentTitle"><%= @article.title.capitalize %></h1>
	<% if @article.categories.any? %>
		<div class="categories">
			Categorías:
			<ul>
				<% @article.categories.each do |cat| %>
					<li><%= cat.name %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	
	<div class="contentBody">
		<%=markdown @article.contents %>
	</div>

	<% if @article.users.any? %>
		<div class="authors">
		Autores:
		<ul>
			<% @article.users.each do |u| %>
				<li><%= link_to u.name, u %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	
	<div id="messages">
		<h3 class="contentTitle">Comentarios</h3>
			<ul>
				<% for msg in @article.messages do %>
					<%= render :partial => 'message', :locals => { :message => msg } %>
				<% end %>
			</ul>
		<h3 class="contentTitle">Escribir un comentario</h3>
		<% if logged_in? %>
			<div class="nuevoMensaje">
				<%= semantic_form_for @message do |f| %>
					<%= f.inputs do %>
						<%= f.input :article_id, :as => :hidden, :input_html => { :value => @article.id }%>
						<%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
						<%= f.input :message, :as => :text, :input_html => { :value => '' },:label => false %>
					<% end %>
					<%= f.buttons do %>
						<%= f.commit_button %>
					<% end %>
				<% end %>
			</div>
		<% else %>
			<div style="font-size: 15px; padding: 25px; border: 1px solid gray; margin: 10px;">
				Debes estar logueado para poder crear mensajes.<br/>
				<%= link_to "Ingresar", login_path %> | <%= link_to "Nuevo?", signup_path %>
			</div>
		<% end %>
	</div>
	
	
	<% if editor? && @article.users.include?(current_user) || admin?  %>
		<%= link_to 'Editar', edit_article_path(@article) %> |
	<% end %>
	
	<%= link_to 'Volver a Arículos', articles_path %>
</div>