config/routes.rb
EnsaludpsiRails::Application.routes.draw do  
  resources :messages

  resources :categories

  resources :articles

  resources :users
  resources :sessions
  
  resources :questions
  
  root                  :to => 'pages#home'
  
  match '/matypat',     :to => 'pages#mat_y_pat'
  match '/consultorio', :to => 'pages#consultorio'
  match '/contacto',    :to => 'pages#contacto'
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new",     :as => "login"
  get "signup" => "users#new",        :as => "signup"

  match "/toggle_admin" => "users#toggle_admin"
  match "/toggle_editor" => "users#toggle_editor"


end

app/views/pages/_actions.html.erb
<% if editor? || admin? %>
	<div class="contents">
		<h1 class="contentTitle">Acciones</h1>
		<div class="acciones">
			<ul>
				<% if editor? %>
					<li><%= link_to "Artículo nuevo", new_article_path %></li>
				<% end %>
				<% if editor? || admin? %>
					<li><%= link_to "Categoría nueva", new_category_path %></li>
				<% end %>
				<% if admin? %>
					<li><%= link_to "Administrar usuarios", users_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>

app/views/pages/consultorio.html.erb
<div class="contents">
	<h1 class="contentTitle">Consultorio</h1>
	<div class="contentBody">
		<ul>
			<li>Terapia de familia</li>
			<li>Terapia de pareja</li>
			<li>Grupo terapéutico</li>
			<li>Asesoramiento psicológico</li>
		</ul>
	</div>
</div>

app/views/pages/contacto.html.erb
<div class="contents">
  <h1 class="contentTitle">Redes Sociales</h1>
  <div class="contentBody">
    <a href="http://www.facebook.com/profile.php?id=100001450706252">
      <center><%= image_tag "/assets/facebook.png" %></center>
    </a>		
  </div>
</div>

<div class="contents">
  <h1 class="contentTitle">Realizar una consulta</h1>
  
	<%= render "shared/flash_messages" %>
  
	<% unless @question.errors.empty? %>
  <div class="error_messages">
		<%= render "shared/error_message", :target => @question.errors[:name], :field_name => t("activerecord.models.question.attributes.name") %>
		<%= render "shared/error_message", :target => @question.errors[:from], :field_name => t("activerecord.models.question.attributes.from") %>
		<%= render "shared/error_message", :target => @question.errors[:subject], :field_name => t("activerecord.models.question.attributes.subject") %>
		<%= render "shared/error_message", :target => @question.errors[:question], :field_name => t("activerecord.models.question.attributes.question") %>
  </div>
	<% end %>
  
  <div class="contentBody">
    <%= form_for @question do |f| %>			
			<div class="field">
				<%= f.label t("activerecord.models.question.attributes.name") %>
				<%= f.text_field :name %>
			</div>
			<div class="field">
				<%= f.label t("activerecord.models.question.attributes.from") %>
				<%= f.text_field :from %>
			</div>
			<div class="field">
				<%= f.label t("activerecord.models.question.attributes.subject") %>
				<%= f.text_field :subject %>
			</div>
			<div class="field">
				<%= f.label t("activerecord.models.question.attributes.question") %>
				<%= f.text_area :question, :rows => "8" %>
			</div>
			<div class="actions"><%= submit_tag "Realizar consulta" %></div>
		<% end %>
  </div>  
</div>

app/views/pages/home.html.erb
<%= render "actions" %>

<div class="contents">
  <h1 class="contentTitle">Lic. Gimena Galarraga</h1>
  <div class="contentBody">
		<center>
		<table>
			<tr>
				<td style="padding: 20px;">
					<div id="cvfoto"><%= image_tag "CVfoto.jpg" %></div>
				</td>
				<td style="padding: 20px;">
					<center style="font-size:20px; line-height:150%">
						<p>Bienvenidos!</p>
						<p>En Salud Psi es un proyecto que busca alcanzar la salud de una manera integradora.</p>
						<p>Para alcanzar este objetivo utilizamos diferentes herramientas, que se acomodan a las necesidades de los consultantes.</p>
						<p>La filosofía que manejamos es el trabajo con y para la prevención.</p>
					</center>
				</td>
			</tr>
		</table>
		
		</center>
  </div>
</div>
<div class="contents">
  <h1 class="contentTitle">Podés visitarnos en Facebook</h1>
  <div class="contentBody">
    <a href="http://www.facebook.com/profile.php?id=100001450706252">
      <center><%= image_tag "/assets/facebook.png" %></center>
    </a>	
  </div>
</div>

<div class="contents">
  <h1 class="contentTitle">Consultas</h1>
  <div class="contentBody">
			Para realizar consultas sobre nuestros servicios, podés acceder a nuestra <%= link_to "página de contacto", contacto_path %>.
  </div>
</div>

app/views/pages/mat_y_pat.html.erb
<h1 class="contentsTitle">Maternidad y Paternidad</h1>
  
<div class="contents">
  <h2 class="contentTitle">Preparación Domiciliaria para el Parto/Cesárea</h2>
  <div class="contentBody">
    Para parejas que por alguna razón no puedan realizar el curso de preparto en una institución. Se tratarán diferentes temas relativos a la Maternidad y la Paternidad, la Lactancia, el Parto/cesárea, Relajación, etc.
    Los horarios se acuerdan entre el terapeuta y los interesados.
  </div>
  <div class="Duracionmatypat">
		Duracción:
    4 encuentros de 1 hora y media / 2 horas cada uno.
  </div>
</div>
<div class="contents">
  <h2 class="contentTitle">Asesoramiento en Lactancia a Domicilio u Hospitalaria</h2>
  <div class="contentBody">
    Los encuentros se realizan de manera particular, ya sea antes o después de que nazca el Bebé.
    Los temas generales a tratar son:
    <ul>
			<li>¿Cómo alcanzar una lactancia exitosa y satisfactoria?</li>
			<li>Beneficios de la Lactancia Materna</li>
			<li>Propiedades de la leche</li>
			<li>Lactancia y reinserción laboral</li>
		</ul>
    <div class="Duracionmatypat">
    Duracción:
    Se acuerda con los solicitantes la cantidad de encuentros, dependiendo de las necesidades particulares de cada caso.
    La información teórico-práctica, se envía via mail y se realizan seguimientos telefónicos.
  </div>
</div>
  </div>
  <div class="contents">
  <h2 class="contentTitle">Consultorio para diagnóstico y tratamiento de problemáticas relacionadas con la Lactancia</h2>
  <div class="Duracionmatypat">
    Duracción:
    Un encuentro diagnóstico. Dependiendo de este encuentro se estructura la cantidad de visitas necesarias.
    La información teórico-práctica, se envía via mail y se realizan seguimientos telefónicos.
  </div>
</div>
<div class="contents">
  <h2 class="contentTitle">Asesoramiento en Crianza</h2>
  <div class="contentBody">
    La modalidad de trabajo puede ser individual o en grupos. Se va a trabajar sobre la demanda que se plantee en cada encuentro.
  </div>
  <div class="Duracionmatypat">
    Duracción:
    Cada encuentro es de 1 hora.
  </div>
</div>
<div class="contents">
  <h2 class="contentTitle">Doula - Acompañamiento emocional previo al parto, durante el parto y postparto. </h2>
  <div class="contentBody">
    <b>¿Qué es ser una Doula?</b>
    <ul>
      Una Doula es una persona que acompaña tanto a la embarazada como a su pareja durante el preparto, el parto y el puerperio, ofreciendo un apoyo emocional continuo.
    </ul>
    <b>Características de una Doula</b>
    <ul>
      <li><b>Ser Mujer:</b> Durante un momento de stress, el cuerpo segrega catecolaminas (sustancia que incluye la adrenalina), esto trae como resultado demoras en el parto, menor flujo sanguíneo y alteraciones en el ritmo cardíaco del bebe. Según algunos autores, la respuesta femenina ante el stress, es agruparse, asociarse y cuidarse. Es por esta razón que se cree que el contacto continuo con otra mujer reduciría esta respuesta.</li>
      <li><b>Proporcionar apoyo emocional: </b>El rol de la Doula es el de ofrecer un apoyo emocional constante, sin juzgar. Debe permitir y propiciar que la mujer y su pareja sean los protagonistas de ese momento de su vida.</li>
      <li><b>Apoyar tanto a la embarazada como a su pareja: </b>El rol de la Doula difiere del rol del padre porque ésta no se encuentra involucrada de la misma manera él. De todas maneras creemos que el valor de la presencia del padre es incalculable y que ambos roles no se superponen.</li>
      <li><b>Favorecer y estimular el vinculo entre el equipo de salud y la pareja:</b> La Doula puede desempeñarse como mediador con el equipo médico, dado que puede explicarle a la pareja lo que va ocurriendo así como trasmitirle al equipo las necesidades de la pareja.</li>
      <li><b>Presencia continua:</b> Esto implica que la Doula va a permanecer con la pareja el tiempo que sea necesario. Esto produce disminución del stress y sensación de seguridad.</li>
    </ul>
    <b>Algunos beneficios de tener una Doula como acompañante:</b>
    <ul>
			<i>
      <li>Menor incidencia de Cesárea en un 51%.</li>
      <li>Menor duración del trabajo de parto.</li>
      <li>Mayor porcentaje de Parto Natural.</li>
      <li>Disminuye la necesidad de anestesia y analgesia.</li>
      <li>Efecto psicológico positivo a corto y largo plazo.</li>
      </i>
    </ul>
    <b>Actividades:</b>
    <ul>
      <li>Charla informativa gratuita.</li>
      <li>Entrevista individual con la pareja. Aquí se plantearan las necesidades particulares y conjuntamente se delineará el plan particular.</li>
      <li>Encuentros preparto</li>
      <li>Acompañamiento durante el parto</li>
      <li>Visita postparto</li>
    </ul>
  </div>
  <div class="Duracionmatypat">
    Duracción:
    Dependerá de lo acordado con los consultantes .
  </div>
</div>
<div class="contents">
  <h2 class="contentTitle">Reflexología para embarazo, parto y puerperio.</h2>
  <div class="contentBody">
		<p>La reflexología es la terapia de tratamiento que se basa en el principio de que hay zonas reflejas en pies, en la cara y en las manos, que se corresponden con todas las glándulas, órganos y partes del cuerpo. </p>
		<p>En la reflexología se emplea el pulgar y los dedos para aplicar presiones específicas a estos puntos reflejos y lograr así numerosos beneficios terapéuticos.</p>
		<p>Se trabaja cada reflejo, desencadenando con ello una liberación del estrés y la tensión en la zona correspondiente del cuerpo,también lográndose una respuesta general de relajación. Esta liberación de la tensión desbloquea los impulsos nerviosos y mejora el suministro sanguíneo a todas las partes del cuerpo. Dado que la reflexología trabaja sobre el reflejo del órgano completo, el efecto equilibrador se produce sobre cada glándula, órgano y región del cuerpo. Habitualmente, los clientes expresan alivio de la tensión y el dolor, una mayor sensación de bienestar y el aumento de su energía. Así también se normaliza el flujo sanguíneo linfático hacia diversas zonas del cuerpo, activando la oxigenación de los tejidos y la eliminación los desechos.</p>
		<p>En cada pie encontramos 7.200 terminaciones nerviosas, éstas tienen extensas interconexiones, que van por la médula espinal, el cerebro y se distribuyen por todo el cuerpo, es por esta razón que el trabajar sobre los reflejos se convierte en un instrumento eficaz para liberar la tensión e intensificar la buena salud.</p>
    <b>Algunas problemáticas que se alivian y/o solucionan con el uso de la reflexología:</b>
    <ul>
      <li>Nauseas, malestar y mareos.</li>
      <li>Acidéz y ardor estomacal.</li>
      <li>Estreñimiento, problemas digestivos y hemorroides.</li>
      <li>Anemia.</li>
      <li>Diabetes Gestacional.</li>
      <li>Síndrome del Túnel Carpiano.</li>
      <li>Dolor de Espalda y Ciático.</li>
      <li>Disfunción de Sínfisis Púbica.</li>
      <li>Edema y retensión de líquidos.</li>
      <li>Estimulación y sedación de contracciones.</li>
      <li>Entre otras ...</li>
    </ul>
  </div>
  <div class="Duracionmatypat">
    Duracción:
    Cada encuentro es de 1 hora.
  </div>
</div>