config/routes.rb
EnsaludpsiRails::Application.routes.draw do  
  resources :messages

  resources :categories

  resources :articles

  resources :users
  resources :sessions
  
  resources :questions
  
  root                  :to => 'pages#home'
  
  match '/matypat',     :to => 'pages#mat_y_pat'
  match '/consultorio', :to => 'pages#consultorio'
  match '/contacto',    :to => 'pages#contacto'
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new",     :as => "login"
  get "signup" => "users#new",        :as => "signup"

  match "/toggle_admin" => "users#toggle_admin"
  match "/toggle_editor" => "users#toggle_editor"


end

app/views/layouts/_header.html.erb
<div id="cabecera">
	<%= render "layouts/logo" %>

	<%= render "layouts/user_menu" %>

	<div id="gandhi">
		<div class="frase">"Sé el cambio que quieras ver en el mundo"</div>
		<div class="firma">- Mohandas Gandhi</div>
	</div>
</div>

app/views/layouts/_left.html.erb
<div id="leftSidebar" class="">
	<%= yield :left_bar %>
</div>

app/views/layouts/_logo.html.erb
<%= link_to image_tag("/assets/ensaludpsiLogo.png", :id => "logo"), root_path %>
<div id="nombre">
	En Salud Psi
	<p>Lic. Gimena Galarraga</p>
</div>

app/views/layouts/_menu.html.erb
<div id="menu">
	<ul>
		<li class="menuItem"><%= link_to "Inicio", root_path %></li>
		<li class="menuItem"><%= link_to "Maternidad y Paternidad", matypat_path %></li>
		<li class="menuItem"><%= link_to "Artículos", articles_path %></li>
		<li class="menuItem"><%= link_to "Consultorio", consultorio_path %></li>
		<li class="menuItem"><%= link_to "Contacto", contacto_path %></li>
	</ul>
</div>

app/views/layouts/_right.html.erb
<div id="rightSidebar" class="">
	
</div>

app/views/layouts/_user_menu.html.erb
<nav id="userMenu">
	<ul>
	<% if logged_in? %>
		<!-- <li>Avatar</li> -->
		<li><%= link_to "#{current_user.name}", user_path(current_user) %></li>
		<li><%= link_to "Perfil", edit_user_path(current_user) %></li>
		<% if admin? %>
			<li><%= link_to "Usuarios", users_path %></li>
		<% end %>
		<li><%= link_to "Salir", logout_path %></li>
	<% else %>
		<li><%= link_to "Ingresar", login_path %></li>
		<li><%= link_to "Nuevo?", signup_path %></li>
	<% end %>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>En Salud Psi <%= " - #{@title}"  if @title %></title>
  <%= stylesheet_link_tag    "application", "formtastic_base" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="principal">
		<%= render "layouts/header" %>
		<div id="centro">
			<%= render "layouts/left" %>
			<div id="contents" class="">
				<%= render "layouts/menu" %>
				
				<% if admin? && published_articles(false).any? %>
					<div class="contents">
						<div class="error_messages">
							<h1 class="contentTitle">Hay artículos pendientes de publicar</h1>
							<div class="contentBody">
								<ul>
									<% published_articles(false).each do |article| %>
										<li><strong><%= link_to article.title.capitalize, edit_article_path(article) %></strong> (<%= link_to 'Eliminar', article, :confirm => 'Está seguro?', :method => :delete %>)</li>
									<% end %>
								</ul>
							</div>
						</div>
					</div>
				<% end %>
				
				<%= yield %>
			</div>
			<%= render "layouts/right" %>
		</div>
	</div>


</body>
</html>